apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev-control-plane
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: dev-control-plane
    apps.tanzu.vmware.com/scanning: "true"
    apps.tanzu.vmware.com/workload-type: web
    kustomize.toolkit.fluxcd.io/name: full-cluster
    kustomize.toolkit.fluxcd.io/namespace: tanzu-continuousdelivery-resources
    app.kubernetes.io/component: run
    carto.run/workload-name: dev-control-plane
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/correlationid: https://github.com/cpage-pivotal/Dev.Control.Plane?sub_path=dcp
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/is-native-app-check
          spring-boot-convention/is-prometheus-enabled-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: dev-control-plane
        apps.tanzu.vmware.com/scanning: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: dev-control-plane
        kustomize.toolkit.fluxcd.io/name: full-cluster
        kustomize.toolkit.fluxcd.io/namespace: tanzu-continuousdelivery-resources
    spec:
      containers:
      - image: gcr.io/fe-cpage/tap/workloads/dev-control-plane-workload-corby@sha256:9b7e07da302f7bcb5d4a927e3ce5f751b71f45e27b82d39d15b15587f63a5526
        name: workload
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      serviceAccountName: default

